name: my tests
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 13.x
      uses: actions/setup-node@master
      with:
        node-version: 13.x
      
    - name: Install
      run: yarn install
      
    - name: run tests 
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn run test
